harden cmake deprecation check
It turns out MSVC 2015 passes the CXX14 check for the deprecated
attribute, but then complains when it is used in a constructor:
E:\jenkins\workspace\workspace\dealii-windows-
compile\CC\msvc2015\label\win\include\deal.II/base/table_indices.h(129):
error C2416: attribute 'deprecated' cannot be applied in this context

Fix this.