fix pragma warnings warnings
PR #1076 disabled warnings due to disabling unknown warnings with a
pragma. This causes the warning

src.cxx:4:3: error: unknown warning group '-Wpragmas', ignored [-Werror,-Wunknown-pragmas]
  _Pragma("GCC diagnostic ignored \"-Wpragmas\"")

with Clang 3.4.0. It seems it supports Wunknown-pragmas which is okay to be
used with gcc too. Sigh.